[project]
name = "reparaciones-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.128.0",
  "uvicorn[standard]>=0.40",
  "pydantic>=2.12",
  "pydantic-settings>=2.12",
  "sqlalchemy>=2.0.45",
  "psycopg[binary]>=3.3.2",
]

[tool.uvicorn]
factory = false
